#!/bin/sh

usage=$(awk -v a="$(awk '/cpu /{print $2+$4,$2+$4+$5}' /proc/stat; sleep 1)" '/cpu /{split(a,b," ");
printf 100*($2+$4-b[1])/($2+$4+$5-b[2])}'  /proc/stat);

printf "%.0f%%" $usage 
# sensors | awk '/Core 0/ {print "🌡" $3}'
