#!/bin/sh

# rofi -combi-modi window,drun -theme Arc-Dark -font "hack 15" -show combi
# rofi -theme Arc-Dark -font "hack 15" -show drun
# rofi -theme Arc-Dark -font "hack 15" -show drun
rofi -font "hack 15" -lines 2 -columns 2 -show drun
